[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.2", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
methods = { path = ".." }

[[bin]]
name = "guest"
path = "src/bin/main.rs"