[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.0", features = ["prove"] }
guest = { path = "../guest" }
zk-bug-bounty-methods = { path = "../methods" }
serde = { version = "1.0", features = ["derive"] }