[package]
name = "zk-bug-bounty-methods"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-build = { version = "1.0" }

[build-dependencies]
risc0-build = { version = "1.0" }

[package.metadata.risc0]
methods = ["../guest"]